name:            minijuvix
version:         0.1.2
license:         GPL-3.0-only
license-file:    LICENSE
copyright:       (c) 2022- Heliax AG.
maintainer:      The PLT Team at Heliax AG <hello@heliax.dev>
author:          [ Jonathan Prieto-Cubides , Jan Mas Rovira , Paul Cadman ]
tested-with:     ghc == 9.2.2
homepage:        https://github.com/heliaxdev/minijuvix
bug-reports:     https://github.com/heliaxdev/minijuvix/issues
description:     The MiniJuvix compiler
category:        Compilers/Interpreters
github:          heliaxdev/minijuvix

extra-source-files:
- README.org
- CHANGELOG.org

dependencies:
- aeson == 2.0.*
- base == 4.16.*
- blaze-html == 0.9.*
- blaze-markup == 0.8.*
- bytestring == 0.11.*
- containers == 0.6.*
- directory == 1.3.*
- edit-distance == 0.2.*
- extra == 1.7.*
- transformers == 0.5.*
- filepath == 1.4.*
- gitrev == 1.3.*
- hashable == 1.4.*
- megaparsec == 9.2.*
- microlens-platform == 0.4.*
- parser-combinators == 1.3.*
- polysemy == 1.7.*
- polysemy-plugin == 0.4.*
- prettyprinter == 1.7.*
- prettyprinter-ansi-terminal == 1.1.*
- process == 1.6.*
- semirings == 0.6.*
- singletons == 3.0.*
- singletons-th == 3.1.*
- Stream == 0.4.*
- template-haskell == 2.18.*
- text == 1.2.*
- th-utilities == 0.2.*
- unordered-containers == 0.2.*

# the tasty dependencies are here to avoid having to recompile
# minijuvix when running the tests.
- tasty
- tasty-hunit
- Diff == 0.4.*
- pretty-show == 1.10.*

ghc-options:
# Warnings
- -Wall
- -Wcompat
- -Wderiving-defaults
- -Widentities
- -Wincomplete-patterns
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-deriving-strategies
- -Wredundant-constraints
# HIE Support
- -fhide-source-paths
- -fwrite-ide-info -hiedir=.hie
# Polysemy Support
- -O2 -flate-specialise -fspecialise-aggressively

default-extensions:
- DataKinds
- DerivingStrategies
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- QuasiQuotes
- RecordWildCards
- TemplateHaskell
- TypeFamilyDependencies
- UnicodeSyntax

library:
  source-dirs: src
  verbatim:
    default-language: GHC2021

executables:
  minijuvix:
    main: Main.hs
    source-dirs: app
    dependencies:
    - ansi-terminal == 0.11.*
    - minijuvix
    - optparse-applicative == 0.17.*
    verbatim:
      default-language: GHC2021

tests:
  minijuvix-test:
    main:                Main.hs
    source-dirs:         test
    dependencies:
    - minijuvix
    verbatim:
      default-language: GHC2021
