ghc-options:
  "$locals": -optP-Wno-nonportable-include-path
resolver: nightly-2024-02-06
extra-deps:
  - resourcet-effectful-1.0.1.0
  - git: https://github.com/haskell-effectful/effectful.git
    commit: 2037be9a4f4e8f8fd280d9359b1bc7feff9b29b9
    subdirs:
      - effectful-th
  - git: https://github.com/Vekhir/aeson-better-errors.git
    commit: 1ec49ab7d1472046b680b5a64ae2930515b47714
allow-newer: true
allow-newer-deps:
  - aeson-better-errors
  - effectful-th
