FROM alpine:3.16
ARG GHC_BOOTSTRAP_VERSION=9.0.2
ARG GHC_VERSION=9.4.5
ARG STACK_VERSION=2.11.1
ARG GHC_ALPINE_VERSION=3.12

RUN apk upgrade --no-cache &&\
    apk add --no-cache curl gcc g++ gmp-dev ncurses-dev libffi-dev make xz gzip tar perl git bash sudo binutils-gold lld &&\
    apk add --no-cache zlib zlib-dev zlib-static gmp gmp-dev ncurses-static xz alex happy python3

RUN curl https://downloads.haskell.org/~ghc/$GHC_BOOTSTRAP_VERSION/ghc-$GHC_BOOTSTRAP_VERSION-x86_64-alpine$GHC_ALPINE_VERSION-linux-gmp.tar.xz -OL

RUN tar xf ghc-$GHC_BOOTSTRAP_VERSION-x86_64-alpine$GHC_ALPINE_VERSION-linux-gmp.tar.xz

RUN cd ghc-$GHC_BOOTSTRAP_VERSION-x86_64-unknown-linux && ./configure --prefix /opt && make install

RUN curl https://downloads.haskell.org/~ghc/$GHC_VERSION/ghc-$GHC_VERSION-src.tar.xz -OL

RUN tar xf ghc-$GHC_VERSION-src.tar.xz

WORKDIR /ghc-$GHC_VERSION

RUN GHC=/opt/bin/ghc ./configure --prefix /usr/local

RUN make -j
RUN make install

RUN apk add --no-cache clang llvm

WORKDIR /

RUN curl https://github.com/commercialhaskell/stack/releases/download/v$STACK_VERSION/stack-$STACK_VERSION-linux-x86_64.tar.gz -OL
RUN tar xf stack-$STACK_VERSION-linux-x86_64.tar.gz
RUN cp stack-$STACK_VERSION-linux-x86_64/stack /usr/local/bin
