(defpackage #:test003
  (:shadowing-import-from :geb.lambda.spec #:func #:pair)
  (:shadowing-import-from :geb.spec #:case)
  (:use #:common-lisp #:geb.lambda.spec #:geb))

(in-package :test003)

(defparameter *entry*
  (typed
    (app
      (coprod
        so1
        (coprod
          (coprod
            so1
            so1)
          (prod
            (coprod
              so1
              so1)
            (coprod
              so1
              so1))))
      (coprod
        so1
        so1)
      (lamb
        (coprod
          so1
          (coprod
            (coprod
              so1
              so1)
            (prod
              (coprod
                so1
                so1)
              (coprod
                so1
                so1))))
        (coprod
          so1
          so1)
        (case-on
          so1
          (coprod
            (coprod
              so1
              so1)
            (prod
              (coprod
                so1
                so1)
              (coprod
                so1
                so1)))
          (coprod
            so1
            so1)
          (index 0)
          (lamb
            so1
            (coprod
              so1
              so1)
            (right
              so1
              so1
              unit))
          (lamb
            (coprod
              (coprod
                so1
                so1)
              (prod
                (coprod
                  so1
                  so1)
                (coprod
                  so1
                  so1)))
            (coprod
              so1
              so1)
            (case-on
              (coprod
                so1
                so1)
              (prod
                (coprod
                  so1
                  so1)
                (coprod
                  so1
                  so1))
              (coprod
                so1
                so1)
              (index 0)
              (lamb
                (coprod
                  so1
                  so1)
                (coprod
                  so1
                  so1)
                (app
                  (coprod
                    so1
                    so1)
                  (coprod
                    so1
                    so1)
                  (lamb
                    (coprod
                      so1
                      so1)
                    (coprod
                      so1
                      so1)
                    (index 0))
                  (index 0)))
              (lamb
                (prod
                  (coprod
                    so1
                    so1)
                  (coprod
                    so1
                    so1))
                (coprod
                  so1
                  so1)
                (app
                  (coprod
                    so1
                    so1)
                  (coprod
                    so1
                    so1)
                  (app
                    (coprod
                      so1
                      so1)
                    (!->
                      (coprod
                        so1
                        so1)
                      (coprod
                        so1
                        so1))
                    (lamb
                      (coprod
                        so1
                        so1)
                      (!->
                        (coprod
                          so1
                          so1)
                        (coprod
                          so1
                          so1))
                      (lamb
                        (coprod
                          so1
                          so1)
                        (coprod
                          so1
                          so1)
                        (case-on
                          so1
                          so1
                          (coprod
                            so1
                            so1)
                          (index 1)
                          (lamb
                            so1
                            (coprod
                              so1
                              so1)
                            (index 2))
                          (lamb
                            so1
                            (coprod
                              so1
                              so1)
                            (index 1)))))
                    (fst
                      (coprod
                        so1
                        so1)
                      (coprod
                        so1
                        so1)
                      (index 0)))
                  (snd
                    (coprod
                      so1
                      so1)
                    (coprod
                      so1
                      so1)
                    (index 0))))))))
      (right
        so1
        (coprod
          (coprod
            so1
            so1)
          (prod
            (coprod
              so1
              so1)
            (coprod
              so1
              so1)))
        (right
          (coprod
            so1
            so1)
          (prod
            (coprod
              so1
              so1)
            (coprod
              so1
              so1))
          (pair
            (coprod
              so1
              so1)
            (coprod
              so1
              so1)
            (right
              so1
              so1
              unit)
            (left
              so1
              so1
              unit)))))
    (coprod
      so1
      so1)))
