-- | Generic class of errors generated by the juvix compiler. Inspired by
-- Control.Exception
module Juvix.Prelude.Error
  ( module Juvix.Prelude.Error,
    module Juvix.Prelude.Error.GenericError,
  )
where

import Juvix.Prelude.Base
import Juvix.Prelude.Error.GenericError

data JuvixError
  = forall a. (ToGenericError a, Typeable a) => JuvixError a

instance ToGenericError JuvixError where
  genericError (JuvixError e) = genericError e

fromJuvixError :: Typeable a => JuvixError -> Maybe a
fromJuvixError (JuvixError e) = cast e
