* Monomorphization
 Monomorphization refers to the process of converting polymorphic code to
 monomorphic code (no type variables) through static analysis.

 Example:
 #+begin_src minijuvix
 id : (A : Type) → A → A;
 id _ a ≔ a;

 b : Bool;
 b ≔ id Bool true;

 n : Nat;
 n ≔ id Nat zero;
 #+end_src

 Is translated into:
 #+begin_src minijuvix
 id_Bool : Bool → Bool;
 id_Bool a ≔ a;

 id_Nat : Nat → Nat;
 id_Nat a ≔ a;
 #+end_src

* More examples
** Mutual recursion
#+begin_src minijuvix
inductive List (A : Type) {
  nil : List A;
  cons : A → List A → List A;
};

even : (A : Type) → List A → Bool;
even A nil ≔ true ;
even A (cons _ xs) ≔ not (odd A xs) ;

odd : (A : Type) → List A → Bool;
odd A nil ≔ false ;
odd A (cons _ xs) ≔ not (even A xs) ;

-- main ≔ even Bool ..  odd Nat;
#+end_src

* Algorithm
** Assumptions:
1. Type abstractions only appear at the leftmost part of a type signature.
2. All functions and constructors are fully type-applied: i.e. currying for
   types is not supported.
3. The =main= function is the entry point and has a concrete type.
4. All axioms are monomorphic.

** Definitions
1. *Application*. An application is an expression of the form =t₁ t₂ … tₙ= with n > 0.

2. *Sub application*. If =t₁ t₂ … tₙ= is an application then for every =0<i<n=
   =t₁ t₂ … tᵢ= is a sub application.

Fix a minijuvix program =P=. Let =𝒲= be the set of all applications that appear in =P=.
1. *Proper application*. A proper application is an application =A∈𝒲= such that
   for every =A'∈𝒲= we have that =A= is *not* a sub application of =A'=.

2. *Type application*. If =t a₁ a₂ … aₙ= is a proper application and =a₁, …, aₘ=
   and =aₘ₊₁= is not a type or =m=n= are types, then =t a₁, …, aₘ= is a type
   application.

3. *Concrete type*. A type is concrete if it involves no type variables.

4. *Concrete type application*. A type application =t a₁ a₂ … aₙ= if =a₁, a₂, …,
   aₙ= are concrete types.

** Option 1
  Gather all type applications in =main=. Since =main= type is concrete, these
  type applications are all concrete. We now have a stack =c₁, c₂, …, cₙ= of
  concrete type applications.
  1. If the stack is empty, we are done.
  2. Otherwise pop =c₁= from the stack. It will be of the form =t a₁ … aₘ=,
     where =t= is either a constructor or a function and =a₁, …, aₘ= are
     concrete types.
  3. If the instantiation =t a₁ … aₘ= has already been registered go to step 1.
     Otherwise continue to the next step.
  4. Register the instantiation =t a₁ … aₘ=.
  5. If =t= is a constructor continue to step 1.
  6. If =t= is a function, then it has type variables =v₁, …, vₘ=.
     Consider the substitution =σ = {v₁ ↦ a₁, …, vₘ ↦ aₘ}=.
     Consider the list of type applications in the body of =t=: =d₁, …,dᵣ=.
     Add =σ(d₁), …, σ(dᵣ)= to the stack and continue to step 1.
     It is easy to see that for any =i=, =σ(dᵢ)= is a concrete type application.

*** Correctness
   It should be clear that the algorithm terminates and registers all
   instantiations of constructors and functions.
