-- | Generic class of errors generated by the minijuvix compiler. Inspired by
-- Control.Exception
module MiniJuvix.Prelude.Error
  ( module MiniJuvix.Prelude.Error,
    module MiniJuvix.Syntax.Concrete.Loc,
    module MiniJuvix.Prelude.Error.GenericError,
  )
where

import MiniJuvix.Prelude.Base
import MiniJuvix.Prelude.Error.GenericError
import MiniJuvix.Syntax.Concrete.Loc

data MiniJuvixError
  = forall a. (ToGenericError a, Typeable a) => MiniJuvixError a

instance ToGenericError MiniJuvixError where
  genericError (MiniJuvixError e) = genericError e

fromMiniJuvixError :: Typeable a => MiniJuvixError -> Maybe a
fromMiniJuvixError (MiniJuvixError e) = cast e
