* CLI

** Usage

#+begin_src shell
juvix [Global options]  ((-v|--version) | --show-root | COMMAND)
#+end_src

** Informative options

- =-v,--version=
  Print the version and exit
- =--show-root=
  Print the detected root of the project
- =-h,--help=
  Show this help text


** Global Command flags

- =--no-colors=
  Disable globally ANSI formatting
- =--show-name-ids=
  Show the unique number of each identifier when pretty
                          printing
- =--only-errors=
  Only print errors in a uniform format (used by
                          juvix-mode)

** Main Commands

- =html=
  Generate HTML output from a Juvix file

- =typecheck=
  Typecheck a Juvix file

- =compile=
  Compile a Juvix file

** Dev Commands

#+begin_src shell
juvix dev COMMAND
#+end_src

- =parse=
  Parse a Juvix file
- =scope=
  Parse and scope a Juvix file
- =termination=
  Subcommands related to termination checking
- =internal=
  Subcommands related to Internal
- =minic=
  Translate a Juvix file to MiniC

** CLI Auto-completion Scripts

The Juvix CLI can generate auto-completion scripts. Follow the instructions below for your shell.

NB: You may need to restart your shell after installing the completion script.

*** Bash

Add the following line to your bash init script (for example =~/.bashrc=).

#+begin_src shell
  eval "$(juvix --bash-completion-script juvix)"
#+end_src

*** Fish

Run the following command in your shell:

#+begin_src shell
juvix --fish-completion-script juvix
  > ~/.config/fish/completions/juvix.fish
#+end_src

*** ZSH

Run the following command in your shell:

#+begin_src shell
juvix --zsh-completion-script juvix > $DIR_IN_FPATH/_juvix
#+end_src

where =$DIR_IN_FPATH= is a directory that is present on the [[https://zsh.sourceforge.io/Doc/Release/Functions.html][ZSH FPATH variable]] (which you can inspect by running =echo $FPATH= in the shell).
