
/*
 * This file contains global configuration defines. These defines are normally
 * generated by the compiler. The file here only documents the available values.
 */

#if !defined(ARCH_WASM32) && !defined(ARCH_NATIVE32) && \
    !defined(ARCH_NATIVE64) && !defined(ARCH_ZKLLVM)
#define ARCH_WASM32
// #define ARCH_NATIVE32
// #define ARCH_NATIVE64
// #define ARCH_ZKLLVM
#endif

#if !defined(API_LIBC) && !defined(API_WASI) && !defined(API_ZKLLVM) && \
    !defined(API_NONE)
#define API_WASI
// #define API_LIBC
// #define API_ZKLLVM
// #define API_NONE
#endif

#if !defined(DEBUG) && !defined(NDEBUG)
#define DEBUG
// #define NDEBUG
#endif

// #define NO_GC
