
/*
 * This file contains global configuration defines. These defines are normally
 * generated by the compiler. The file here only documents the available values.
 */

#if !defined(ARCH_WASM32) && !defined(ARCH_NATIVE32) && !defined(ARCH_NATIVE64)
#define ARCH_WASM32
//#define ARCH_NATIVE32
//#define ARCH_NATIVE64
#endif

#if !defined(API_LIBC) && !defined(API_WASI) && !defined(API_ANOMA) && \
    !defined(API_COSM) && !defined(API_NONE)
#define API_WASI
//#define API_LIBC
//#define API_ANOMA
//#define API_COSM
//#define API_NONE
#endif

#if !defined(DEBUG) && !defined(NDEBUG)
#define DEBUG
//#define NDEBUG
#endif

//#define NO_GC
