#+TITLE: Developer Tooling

** Emacs mode

  There is an Emacs mode available for MiniJuvix. Currently, it
  supports syntax highlighting for well-scoped modules.

  To install it add the following lines to your Emacs configuration file:

  #+begin_src elisp
  (push "/path/to/minijuvix/minijuvix-mode/" load-path)
  (require 'minijuvix-mode)
  #+end_src

  Make sure that =minijuvix= is installed in your =PATH=.

  The MiniJuvix major mode will be activated automatically for =.mjuvix= files.

*** Keybindings

  | Key       | Function Name    | Description                                           |
  |-----------+------------------+-------------------------------------------------------|
  | =C-c C-l= | =minijuvix-load= | Runs the scoper and adds semantic syntax highlighting |

** CLI Auto-completion Scripts

The MiniJuvix CLI can generate auto-completion scripts. Follow the instructions below for your shell.

NB: You may need to restart your shell after installing the completion script.

*** Bash

Add the following line to your bash init script (for example =~/.bashrc=).

#+begin_src shell
  eval "$(minijuvix --bash-completion-script minijuvix)"
#+end_src

*** Fish

Run the following command in your shell:

#+begin_src shell
minijuvix --fish-completion-script minijuvix > ~/.config/fish/completions/minijuvix.fish
#+end_src

*** ZSH

Run the following command in your shell:

#+begin_src shell
minijuvix --zsh-completion-script minijuvix > $DIR_IN_FPATH/_minijuvix
#+end_src

where =$DIR_IN_FPATH= is a directory that is present on the [[https://zsh.sourceforge.io/Doc/Release/Functions.html][ZSH FPATH variable]] (which you can inspect by running =echo $FPATH= in the shell).
