* Module system

** Defining a module

Each Juvix file has to define a module of the same name.

#+begin_example
-- Example.juvix
module Example;
-- module content ...
end;
#+end_example

# - Inside a module, other (sub) modules can be declared.

# #+begin_example
# -- Example.juvix
# module Example;
#     module A;
#     end;
# end;
# #+end_example

** Importing external definitions

To bring into the current scope all module definitions from other
external modules, one can use the `import` keyword along with the corresponding module name. This way all imported names are qualified.

#+begin_example
-- A.juvix
module A;
   axiom Nat : Type;
   axiom zero : Nat;
end;

-- B.juvix
module B;
    import A;
    x : A.Nat;
    x := A.zero;
#+end_example

Additionally, one can _open_ an imported module making available its 
names but all unqualified. 

#+begin_example
-- A.juvix
module A;
   axiom Nat : Type;
   axiom zero : Nat;
end;

-- B.juvix
module B;
    import A;
    open A;
    x : Nat;
    x := zero;
#+end_example

However, opening modules may create name collisions if you already have the imported names as definitions in the current module. In this case, Juvix will complain with an error letting you know which symbols is ambiguous. In the module =B= below, the name =a= is ambiguous.

#+begin_example
-- A.juvix
module A;
axiom A : Type;
axiom a : A;
end;

-- B.juvix
module B;
import A;
open A;
axiom a : A;

x := a;
end;
#+end_example

One alternative here is hiding the name =a= as follows.

#+begin_example
-- B.juvix
module B;
import A;
open A hiding {a};

axiom a : A;
x := a;

end;
#+end_example

Now, we can use the =open import= syntax to simplify the =import-open= statements.

Instead of having

#+begin_example
import Prelude;
open Prelude;
#+end_example

We simplify it by the expression:

#+begin_example
open import Prelude;
#+end_example

The `hiding` keyword can be used within an =open-import= statement.

#+begin_example
-- B.juvix
module A;
open import A hiding {a};
axiom a : A;
x := a;
end;
#+end_example


** Public names 

